#!/usr/bin/env bash

# build-aem-images: a script to automate the building of AEM docker images.


# list of images we need built
DOCKER_IMAGES="ubuntu-java aem-base aem-author aem-publish aem-dispatcher"

# files expected by the associated Dockerfiles
REQUIRED_FILES="aem-base/aem-quickstart.jar
aem-base/license.properties
aem-dispatcher/dispatcher.so"

# holds the files marked as missing so we can present a list to the user
MISSING_REQUIRED_FILES=

# detect any missing files, display them to user
for f in $REQUIRED_FILES; do
  if [ ! -e $f ]; then
    echo "Error: Missing required file: '${f}'."
    MISSING_REQUIRED_FILES=true
  fi
done

# exit with error if we don't have requried files
if [ $MISSING_REQUIRED_FILES ]; then
  exit 1
fi

# overrride the list of images with anything passed on the command line to allow
# for quicker image building (since aem-base includes the 600mb jar file).
#
# FIXME: validate passed arguments against list of DOCKER_IMAGES so we don't
# attempt to build something we can't.
if [[ "$@" != "" ]]; then
  DOCKER_IMAGES="$*"
fi

# loop over the list of docker images to build
for image in $DOCKER_IMAGES; do
  echo ">>> Building Docker image: ${image}..."
  # build notes:
  # - remove intermediate docker images
  # - tag the images with the image name
  docker build --force-rm -t ${image} -f ./${image}/Dockerfile ./${image}
  echo
done

echo ">>> Image building complete."
echo
echo "Run 'docker-compose up -d' to start the containers."
