# AEM base image (used by -author and -publish)

FROM ubuntu-java

ENV AEM_VERSION 6.1
# NOTE: we're not using *-runmode-port.jar naming convention for jar because it
# doesn't matter for unpacking. run modes are set via CQ_RUNMODE in the -author
# and -publish Dockerfiles.
ENV AEM_QUICKSTART_FILE aem-quickstart.jar
ENV AEM_USER aem
ENV AEM_WORKING_DIR /opt/aem

# set some common env vars to be used by the -author and -publish images.
#
# NOTE: the following vars are only used by the 'quickstart' script, so they
# don't apply during initial startup (installation) via 'start'.
ENV CQ_VERBOSE    true
ENV CQ_GUI        ''
ENV CQ_NOBROWSER  true
ENV CQ_NOFORK     true

# Add quick-start file and license properties
ADD ./$AEM_QUICKSTART_FILE $AEM_WORKING_DIR/$AEM_QUICKSTART_FILE
ADD ./license.properties $AEM_WORKING_DIR/license.properties

# Create aem user, unpack quickstart jar, and adjust ownership of WORKDIR
RUN groupadd -r $AEM_USER && useradd -r -g $AEM_USER $AEM_USER -d $AEM_WORKING_DIR && \
    java -jar $AEM_WORKING_DIR/$AEM_QUICKSTART_FILE -unpack && \
    chown -R $AEM_USER:$AEM_USER $AEM_WORKING_DIR

USER $AEM_USER

WORKDIR $AEM_WORKING_DIR
