# AEM base image (used by -author and -publish)

FROM ubuntu-java

ENV AEM_VERSION 6.1
# NOTE: we're not using *-runmode-port.jar naming convention for jar because it
# doesn't matter for unpacking
ENV AEM_QUICKSTART_FILE aem-quickstart.jar
ENV AEM_USER aem
ENV AEM_WORKING_DIR /opt/aem

# Add quick-start file and license properties
ADD ./$AEM_QUICKSTART_FILE $AEM_WORKING_DIR/$AEM_QUICKSTART_FILE
ADD ./license.properties $AEM_WORKING_DIR/license.properties

# Create user and unpack AEM quick-start
RUN groupadd -r $AEM_USER && useradd -r -g $AEM_USER $AEM_USER -d $AEM_WORKING_DIR && \
    java -jar $AEM_WORKING_DIR/$AEM_QUICKSTART_FILE -unpack && \
    chown -R $AEM_USER:$AEM_USER $AEM_WORKING_DIR

USER $AEM_USER

WORKDIR $AEM_WORKING_DIR
