#!/bin/bash

# aem-first-boot script
#
# start up AEM, wait until it responds, and then shut it down so it's primed
# for future boots.

# exit immediately if any of the following commands fail
set -e

echo "Local environment variables provided to AEM:"
env | sort | sed -e 's/^/  - /'

echo -n "Starting up (installing/priming) new AEM instance"
crx-quickstart/bin/start
until $(curl -u admin:admin --output /dev/null --silent --head --fail http://localhost:$CQ_PORT); do
  printf '.'
  sleep 5
done
echo "done!"

echo "Stopping AEM..."
crx-quickstart/bin/stop

# TODO: change 'pauseCompaction' to 'false' in /opt/aem/crx-quickstart/launchpad/config/org/apache/jackrabbit/oak/plugins/segment/SegmentNodeStoreService.config

exit 0
